// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khmrodtjeeslugkjljzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtobXJvZHRqZWVzbHVna2psanpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjQ0OTgsImV4cCI6MjA1OTgwMDQ5OH0.Qw-ZUM9hHQIJeGCp_BBbz76h2ysieb6wguvlQP1Jz8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);